name: Get Feed

on:
  schedule:
    - cron: "30 2 * * *" # 6pm IST
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: secret_Yn8sG59wyohwrZ3LRI1CYn4f8p0doxtFOv5rChggoVu
      NOTION_READER_DATABASE_ID: 1e5a327436554eca8b7dae8d127bc06a
      NOTION_FEEDS_DATABASE_ID: fc80c3d41bde48cea392b7f8cb8dda7e
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
